services:
    mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      volumes:
        - /home/docker-volumne/db:/data/db:rw
      ports: 
        - 27018:27017

    api:
      build: 
        context: .
        dockerfile: Dockerfile.production
      env_file:
        .env.production
      volumes:
        - /home/docker-volumne/server:/app/server:rw
      ports: 
        - 3000:3000
        - 4200:4200
      environment:
        NODE_ENV: production
        MONGO_URL: mongodb+srv://admin:123456%40aA@atlascluster.nxofdmq.mongodb.net/construct_db?retryWrites=true&w=majority&appName=AtlasCluster
        DB_NAME: construct_db
        SERVER_URL: http://zenithive.co.uk:3000/
        SERVER_API: http://zenithive.co.uk:3000/api/
        APS_CLIENT_ID : eG4diRxL3qCNbqYTGTlMWvAHVIE8u6PURMfcBakZUsSKyJCw
        APS_CLIENT_SECRET : YGrPi2GGoUPtcUUQWql6iXVZNBCl9GypRmAVqbSN5xGcNQpyX92lgI7OeaU3y49d
        PDFTronWebViewerKey: demo:1716379047602:7fc2b51a0300000000e97c7a4fbf9b9afd690a6692e359ccf12c4c4d3a
      depends_on:
        - mongo_db