services:
    mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      ports: 
        - 27018:27017
      volumes:
        - C:\WORK\mongodb\data:/data/db:rw

    api:
      build: 
        context: .
        dockerfile: Dockerfile
      env_file:
        .env
      volumes:
        - C:\WORK\mongodb\server:/app/server:rw
      ports: 
        - 3000:3000
        - 4200:4200
      environment:
        NODE_ENV: dev
        MONGO_URL: mongodb://mongo_db:27017
        DB_NAME: rof
        SERVER_URL: http://localhost:3000/
        SERVER_API: http://localhost:3000/api/
        APS_CLIENT_ID : eG4diRxL3qCNbqYTGTlMWvAHVIE8u6PURMfcBakZUsSKyJCw
        APS_CLIENT_SECRET : YGrPi2GGoUPtcUUQWql6iXVZNBCl9GypRmAVqbSN5xGcNQpyX92lgI7OeaU3y49d
        PDFTronWebViewerKey : demo:1716379047602:7fc2b51a0300000000e97c7a4fbf9b9afd690a6692e359ccf12c4c4d3a
      depends_on:
        - mongo_db