services:
    mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      ports: 
        - 27018:27017
      volumes:
        - /home/docker-volumne/db:mongo_db

    api:
      build: 
        context: .
        dockerfile: Dockerfile
      env_file:
        .env
      volumes:
        - /home/docker-volumne/server:server
      ports: 
        - 3000:3000
        - 4200:4200
      environment:
        NODE_ENV: dev
        MONGO_URL: mongodb://mongo_db:27017
        DB_NAME: rof
        SERVER_URL: http://localhost:3000/
        SERVER_API: http://localhost:3000/api/
        APS_CLIENT_ID : EbAv1ybr2Va7nowXrmnXPq3ymEhKMG5k
        APS_CLIENT_SECRET : i8uk12vSGTjBMqAL
        PDFTronWebViewerKey : demo:1713377310356:7fec63a3030000000019570e975695a71a7b7a7e9b6c8c3c5f510461a8
      depends_on:
        - mongo_db

volumes:
  mongo_db: 
    external: true
  server: 
    external: true