'use client'
import './global.css';

// import { Provider } from 'react-redux';
// import { PersistGate } from 'redux-persist/integration/react';

import { ApolloProvider, InMemoryCache, ApolloClient } from '@apollo/client';

// import App from './app/app';
// import {persistor, store} from './reducers/store';



const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'http://localhost:3000/graphql',
});


export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body>
        <>
      <ApolloProvider client={client}>
        {children}
        </ApolloProvider>
        </>
        {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
          {/* </PersistGate>
        </Provider> */}
      </body>
    </html>
  );
}
