export const columns = [
   {name: 'PROJECT', uid: 'projName'},
   {name: 'REGION', uid: 'region'},
   {name: 'ORGANISATION', uid: 'orgName'},
   {name: 'STATUS', uid: 'status'},
   {name: 'ACTIONS', uid: 'actions'},
];
export const users = [
   {
      id: 1,
      name: 'ACME East Site',
      role: 'New Delhi',
      team: 'Noida',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'tony.reichert@example.com',
   },
   {
      id: 2,
      name: 'Government Hospital Pune',
      role: 'Pune',
      team: 'docx',
      status: 'paused',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'zoey.lang@example.com',
   },
   {
      id: 3,
      name: 'Example Head office Admin',
      role: 'Daily Site Report',
      team: 'docx',
      status: 'active',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'jane.fisher@example.com',
   },
   {
      id: 4,
      name: 'Salary Expenses',
      role: 'Salary Expenses',
      team: 'xlsx',
      status: 'vacation',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      email: 'william.howard@example.com',
   },
   {
      id: 5,
      name: 'Kristen Copper',
      role: 'Sales Manager',
      team: 'Sales',
      status: 'active',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'kristen.cooper@example.com',
   },
   {
      id: 6,
      name: 'ACME East Site',
      role: 'New Delhi',
      team: 'Noida',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'tony.reichert@example.com',
   },
   {
      id: 10,
      name: 'Kristen Copper',
      role: 'Sales Manager',
      team: 'Sales',
      status: 'active',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'kristen.cooper@example.com',
   },
   {
      id: 8,
      name: 'Example Head office Admin',
      role: 'Daily Site Report',
      team: 'docx',
      status: 'active',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'jane.fisher@example.com',
   },
   {
      id: 7,
      name: 'Government Hospital Pune',
      role: 'Pune',
      team: 'docx',
      status: 'paused',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'zoey.lang@example.com',
   },

   {
      id: 9,
      name: 'Salary Expenses',
      role: 'Salary Expenses',
      team: 'xlsx',
      status: 'vacation',
      age: '28',
      avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
      email: 'william.howard@example.com',
   },
   {
      id: 11,
      name: 'ACME East Site',
      role: 'New Delhi',
      team: 'Noida',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'tony.reichert@example.com',
   },
   {
      id: 12,
      name: 'Kristen Copper',
      role: 'Sales Manager',
      team: 'Sales',
      status: 'active',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'kristen.cooper@example.com',
   },
   {
      id: 13,
      name: 'Example Head office Admin',
      role: 'Daily Site Report',
      team: 'docx',
      status: 'active',
      age: '22',
      avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
      email: 'jane.fisher@example.com',
   },
   {
      id: 14,
      name: 'Government Hospital Pune',
      role: 'Pune',
      team: 'docx',
      status: 'paused',
      age: '25',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
      email: 'zoey.lang@example.com',
   },
   {
      id: 15,
      name: 'ACME East Site',
      role: 'New Delhi',
      team: 'Noida',
      status: 'active',
      age: '29',
      avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
      email: 'tony.reichert@example.com',
   },
   {
      id: 16,
      name: 'Kristen Copper',
      role: 'Sales Manager',
      team: 'Sales',
      status: 'active',
      age: '24',
      avatar: 'https://i.pravatar.cc/150?u=a092581d4ef9026700d',
      email: 'kristen.cooper@example.com',
   },
];
